### ISSUE TITLE
Add XML feed suitable for adding to Zeal / Dash / etc.

### ISSUE THREAD

**Issue by selurvedu** [deuill/xmpp-xep-dash-docset#1]
Example: <https://github.com/hashhar/dash-contrib-docset-feeds/raw/master/RFCs.xml>

It could link to <https://github.com/deuill/xmpp-xep-dash-docset/releases/latest/download/XEPs.tgz> which would automatically redirect to the latest available release.

Also, could you please release a XEP update?

**Comment by deuill** [comment]
Good idea, I'll get on that. Glad you've found this useful thus far!

**Comment by deuill** [comment]
Done, and tagged `2024.1.0`. Thanks for the recommendation here @selurvedu!
